name: CI Build

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  
env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: latest
          check-latest: true

      - name: NPM dependencies
        run: npm ci

      - name: Setup .NET Core V8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Benchmark.csproj

      - name: Build Proj
        run: dotnet build Benchmark.csproj -c Release -f net8.0

      - name: Build sln
        run: dotnet build Benchmark.sln -c Release -f net8.0

      - name: Create Release
        if: matrix.os == 'windows-latest'
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: v1.4.8.3