name: CI Build (Multi-OS)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  
env:
  DOTNET_NOLOGO: true                     
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true 
  DOTNET_CLI_TELEMETRY_OPTOUT: true       

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-15]
        include:
          - os: windows-latest
            artifact_name: Benchmark_win_x64
            publish_rid: win-x64
            file_extension: zip

          - os: macos-15
            artifact_name: Benchmark_osx_arm64
            publish_rid: osx-arm64
            file_extension: tar.gz

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK / .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore Benchmark.csproj

      - name: Build solution
        run: dotnet build Benchmark.sln -c Release -f net9.0

      - name: Publish application
        run: dotnet publish Benchmark.csproj -c Release -r ${{ matrix.publish_rid }} --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None -o publish

      - name: Package artifacts
        shell: bash
        run: |
          if [[ "${{ matrix.file_extension }}" == "zip" ]]; then
            7z a ${{ matrix.artifact_name }}.zip ./publish/*
          else
            tar -czvf ${{ matrix.artifact_name }}.tar.gz -C publish .
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}.${{ matrix.file_extension }}

  Release:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: v1.5.1.2
          artifacts: "artifacts/**"
          artifactContentType: application/octet-stream