name: CI Build

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  
env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore Benchmark.csproj

      - name: Build Proj
        run: dotnet build Benchmark.csproj -c Release -f net7.0

      - name: Build sln
        run: dotnet build Benchmark.sln -c Release -f net7.0

      - name: Create Release
        if: matrix.os == 'windows-latest'
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: v1.4.5.1